### PR TITLE
Add filtering to pokedex

### PR DESCRIPTION
**Pull request by stephenap07**
I also removed some useless build code in gwen.
pokedex_windows_sample

### CODE REVIEW

**Comment by tsweeney256** [comment]
Why aren't you filtering the pokemon using the "characteristics" part of my PokemonData class? That's why I made it. It also allows for more advanced filtering and decouples the data from the interface. You don't need to reimplement the filtering functionality. The example showing how to use it is still in the dropbox account.

**Comment by tsweeney256** [comment]
Also I only just noticed this, but we're going to need to put back the type effectiveness lists on the screen for each pokemon. I can do it, but I don't want to mess up any grand designs you have for the interface.

**Comment by stephenap07** [comment]
I forgot you added that filtering mechanism. I also left out stuff on purpose, I'm currently reimplementing the way stats are displayed.

**Comment by tsweeney256** [comment]
By the way, are you still going to make that advanced filtering button to be able to filter pokemon by their base stats and whatnot? Because that was one of the major reasons behind creating that characteristics part of the PokemonData class.

**Comment by stephenap07** [comment]
I was thinking about using a small query language in the filter text bar to do the filtering. But then again, that's very unintuitive. Perhaps I'll have an 'advanced' tab for filtering with sliders and checkboxes.

**Comment by tsweeney256** [comment]
Yeah that latter one is more along the lines of what I was thinking. We definitely shouldn't be using a query language. In fact, avoiding direct queries is the exact reason I made the pokemonData class.

**Pull request merged**
